apiVersion: v1
kind: Service
metadata:
  name: webtest
  labels:
    app: webtest
spec:
  ports:
  - port: 80
    nodePort: 80
  selector:
    app: webtest
    tier: production
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtest-pv-claim
  labels: 
    app: webtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
  labels:
    app: webtest
spec:
  replicas: 2
  selector:
   matchLabels:
     app: webtest
     tier: production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webtest
        tier: production
    spec:
       containers:
       - image: gauravmehta13/apache-webserver
         name: webtest
         ports:
         - containerPort: 80
           name: webtest
         volumeMounts:
         - name: webtest-vol
           mountPath: /var/www/html
       volumes:
       - name: webtest-vol
         persistentVolumeClaim:
           claimName: webtest-pv-claim